name: stash

channels:
    - astropy

dependencies:
    - python=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - pip:
        - batman-package
        - sphinx-automodapi
        - numpydoc